config/routes.rb
Rails.application.routes.draw do

  root 'dealerships#index'
  resources :dealerships
  resources :cars
  resources :salesmen
  resources :customers
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :dealership
  belongs_to :salesman
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :dealership
  belongs_to :salesman
  has_many :cars
end

app/models/dealership.rb
class Dealership < ActiveRecord::Base
  has_many :cars
  has_many :salesmen
  has_many :customers
end

app/models/salesman.rb
class Salesman < ActiveRecord::Base
  has_many :cars
  has_many :customers
  belongs_to :dealership
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.where(dealership_id: params[:dealership_id])
  end

  def show
  end

  def new
    @car = Car.new(dealership_id: params[:dealership_id])
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to dealership_path(@car.dealership_id)
    else
      alert('error')
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render :edit
    end
  end

  def destroy
    if @car.destroy
      redirect_to dealership_path(@car.dealership_id)
    else
      render :show
    end
  end

  private
  def car_params
    params.require(:car).permit(:make, :model, :year, :color, :mileage, :dealership_id, :salesman_id)
  end

  def find_car
    @car = Car.find(params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :find_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to dealership_path(@customer.dealership_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to dealership_path(@customer.dealership_id)
    else
      render :edit
    end
  end

  def destroy
    if @customer.destroy
      redirect_to dealership_path(@customer.dealership_id)
    else
      render :show
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :age, :budget, :dealership_id, :salesman_id)
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :find_dealership, only: [:show, :edit, :update, :destroy]

  def index
    @dealerships = Dealership.all
  end

  def show
    @cars = Car.where(dealership_id: params[:id])
    @salesmen = Salesman.where(dealership_id: params[:id])
  end

  def new
    @dealership = Dealership.new
  end

  def create
    @dealership = Dealership.new(dealership_params)
    if @dealership.save
      redirect_to dealerships_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @dealership.update(dealership_params)
      redirect_to dealership_path(@dealership)
    else
      render :edit
    end
  end

  def destroy
    if @dealership.destroy
      redirect_to dealerships_path
    else
      render :show
    end
  end

  private
  def dealership_params
    params.require(:dealership).permit(:name, :address, :rating)
  end

  def find_dealership
    @dealership = Dealership.find(params[:id])
  end

end

app/controllers/salesmen_controller.rb
class SalesmenController < ApplicationController
  before_action :find_salesman, only: [:show, :edit, :update, :destroy]

  def index
    @salesmen = Salesman.all
  end

  def show
  end

  def new
    @salesman = Salesman.new(dealership_id: params[:dealership_id])
  end

  def create
    @salesman = Salesman.new(salesman_params)
    if @salesman.save
      redirect_to dealership_path(@salesman.dealership_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @salesman.update(salesman_params)
      redirect_to salesman_path(@salesman)
    else
      render :edit
    end
  end

  def destroy
    if @salesman.destroy
      redirect_to salesmen_path
    else
      render :show
    end
  end

  private
  def salesman_params
    params.require(:salesman).permit(:first_name, :last_name, :age, :license_number, :dealership_id)
  end

  def find_salesman
    @salesman = Salesman.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/helpers/salesmen_helper.rb
module SalesmenHelper
end

app/views/cars/_form.html.haml
= form_for @car do |f|
  = f.label :make
  = f.text_field :make
  %br
  = f.label :model
  = f.text_field :model
  %br
  = f.label :year
  = f.number_field :year
  %br
  = f.label :color
  = f.text_field :color
  %br
  = f.label :mileage
  = f.number_field :mileage
  %br
  = f.hidden_field :dealership_id, :value => params[:dealership_id], required: true
  = f.submit

app/views/cars/edit.html.haml
%h3
  Edit Car Information
= render(partial: 'form')

app/views/cars/index.html.haml
%h1 All Cars
%hr
- if @cars.any?
  %ul
    - @cars.each do |car|
      %li
        = link_to car.make, car_path(car)
        = car.model
        = car.year
        %br
        = car.mileage 
        miles
- else
  %h3 Sorry, we don't have any cars right now

app/views/cars/new.html.haml
%h3
  Add a New Car
= render(partial: 'form')

app/views/cars/show.html.haml
%h1
  = @car.make
  = @car.model
  = @car.year
%h3
  Color:
  = @car.color
%br
%h3
  Mileage:
  = @car.mileage
  miles
%br

app/views/customers/index.html.haml
%h1 Customers
- if @customers.any?
  %ul
    - @customers.each do |customer|
      %li
      = link_to "#{customer.first_name} #{customer.last_name}", customer_path(customer)
      %hr
- else
  %h3
    There are no customers here, unless you are looking to sign up.
= link_to 'Add a Customer', new_customer_path, class: 'btn'

app/views/dealerships/_form.html.haml
= form_for @dealership do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :address
  = f.text_field :address
  %br
  = f.submit

app/views/dealerships/edit.html.haml
%h3
  Edit the Dealership
= render(partial: 'form')
%hr
= link_to 'Dealerships', dealerships_path, class: 'btn'

app/views/dealerships/index.html.haml
%h1 My Dealerships
- if @dealerships.any?
  %ul
    - @dealerships.each do |dealership|
      %li
        %h3
          = link_to dealership.name, dealership_path(dealership)
        = link_to 'Edit', edit_dealership_path(dealership) 
        |
        = link_to 'Delete', dealership_path(dealership), method: :delete

      %hr
- else
  %h3
    No Dealerships Available. Please Add One.

= link_to 'Add New Dealership', new_dealership_path, class: 'btn'

app/views/dealerships/new.html.haml
%h2
  Add a New Dealership
= render(partial: 'form')

= link_to 'Dealerships', dealerships_path, class: 'btn'

app/views/dealerships/show.html.haml
%h3
  = @dealership.name
%h4
  Address: 
  = @dealership.address
%hr
%h4 Our Salesmen:
- if @salesmen.any?
  %ul
    - @salesmen.each do |salesman|
      %li
        Name:
        = salesman.first_name 
        = salesman.last_name
        = link_to 'Edit', edit_salesman_path(salesman)
        |
        = link_to 'Delete', salesman_path(salesman), method: :delete
- else
  %h5
    We have no Salesmen. FIND YOUR OWN CAR.
= link_to 'Add Salesman', new_salesman_path(dealership_id: @dealership), class: 'btn'
%hr
%h4 
  = link_to 'Cars Available:', cars_path(dealership_id: @dealership.id)
- if @cars.any?
  %ul
    - @cars.each do |car|
      %li
      Make:
      = car.make
      |
      Model:
      = car.model
      |
      Year:
      = car.year
      = link_to 'Edit', edit_car_path(car)
      |
      = link_to 'Delete', car_path(car), method: :delete
      %hr
- else
  %h5
    No Cars Currently Available
= link_to 'Add Car', new_car_path(dealership_id: @dealership), class: 'btn'
%hr

= link_to 'Dealerships', dealerships_path, class: 'btn'

app/views/layouts/_nav_bar.html.haml
%nav
  .nav-wrapper
    %a.brand-logo{href: '/'} Cars4U
    %ul#nav-mobile.right
      %li
        %a{href: dealerships_path} 
          Dealerships
      %li
        %a{href: customers_path} 
          Customer Profiles

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Car Dealership
    = stylesheet_link_tag    'application', media: 'all' 
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render(partial: 'layouts/nav_bar')
    .container
      = yield

app/views/salesmen/_form.html.haml
= form_for @salesman do |f|
  = f.label :first_name
  = f.text_field :first_name
  %br
  = f.label :last_name
  = f.text_field :last_name
  %br
  = f.label :age
  = f.number_field :age
  %br
  = f.label :license_number
  = f.number_field :license_number
  %br
  = f.hidden_field :dealership_id, :value => params[:dealership_id], required: true

  = f.submit

app/views/salesmen/edit.html.haml
%h3 Edit Salesman
= render(partial: 'form')

app/views/salesmen/new.html.haml
%h3 Add a Salesman
= render(partial: 'form')